apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        imagePullSecret: ialex-cred
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "100Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deploy        
spec:
  ports:
  - port: 80
    protocol: TCP        
    targetPort: 80       
  selector:
    app: nginx
  type: LoadBalancer     
status:
  loadBalancer: {}  